### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by dietmarw** [comment]
Sorry I missed the #1 pull request earlier which now invalidates your typo fixes. Could you run your fixes again on the new master. I could then tag the v1.1

**Comment by dietmarw** [comment]
@tbeu forget what I said. I only now noticed that @lochel  has his own [upstream repo](https://github.com/lochel/PNlib). So it makes much more sense to point development there. I'm gonna switch this repo to be a fork of his rather than his being a fork this. @lochel I hope that is OK for you. That way you can more dynamically develop and all is automatically mirrored. @lochel

**Comment by tbeu** [comment]
But @lochel's repo is forked from yours.

**Comment by dietmarw** [comment]
well that's easy to change ;-)

**Pull request closed without merging**
